---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-archiver
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-archiver-secret
    creationPolicy: Owner
    template:
      data:
        # Database Init
        INIT_POSTGRES_HOST: "${DB_HOST}"
        INIT_POSTGRES_DBNAME: "{{ .OA_POSTGRES_DB }}"
        INIT_POSTGRES_USER: "{{ .OA_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .OA_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .PG_POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .PG_POSTGRES_SUPER_PASS }}"
        # App Configuration
        DATABASE_URL: "postgresql://{{ .OA_POSTGRES_USER }}:{{ .OA_POSTGRES_PASSWORD }}@${DB_HOST}:5432/{{ .OA_POSTGRES_DB }}"
        JWT_SECRET: "{{ .OA_JWT_SECRET }}"
        MEILI_MASTER_KEY: "{{ .MS_MEILI_MASTER_KEY }}"
        REDIS_PASSWORD: "{{ .DF_DRAGONFLY_PASSWORD }}"
  dataFrom:
    - extract:
        key: open-archiver
      rewrite: [{regexp: {source: (.*), target: OA_$1}}]
    - extract:
        key: dragonfly
      rewrite: [{regexp: {source: (.*), target: DF_$1}}]
    - extract:
        key: cloudnative-pg
      rewrite: [{regexp: {source: (.*), target: PG_$1}}]
    - extract:
        key: meilisearch
      rewrite: [{regexp: {source: (.*), target: MS_$1}}]
