---
# yaml-language-server: $schema=https://schemas.bykaj.io/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app proxmox-ve
spec:
  hostnames:
    - pve.${DOMAIN_APP}
  parentRefs:
    - name: envoy-services
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: *app
      matches:
        - path:
            type: PathPrefix
            value: /
      sessionPersistence: # NOT WORKING YET, DO NOT COPY
        sessionName: proxmox-ve-session
        type: Cookie
        absoluteTimeout: 3600s
        cookieConfig:
          lifetimeType: Permanent