---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/issuer_v1.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: postgres-ca
spec:
  ca:
    secretName: postgres-ca-secret
