---
# yaml-language-server: $schema=https://schemas.bykaj.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-archiver
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # components:
  #   - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/default/open-archiver/app
  postBuild:
    substitute:
      APP: *app
      APP_NAME: "Open Archiver"
      APP_SUBDOMAIN: "mailbackup"
      # VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
