---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
spec:
  isCA: true
  commonName: cluster-ca
  secretName: cluster-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-client-ca
spec:
  isCA: true
  commonName: postgres-client-ca
  secretName: postgres-client-ca-secret
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
